version: "3.7"
services:
  postgresql:
    image: postgres:latest
    container_name: postgresql
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=rlence
      - POSTGRES_PASSWORD=rlencepassword